### ISSUE TITLE
Review content in Health Status Evaluation and Outcomes

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#104]
Mock up content and labels i.e., separate out vital signs from "clinical tests". Review all labels to ensure they make sense on this tab.

**Comment by emmanurse** [comment]
See attached requirements[https://app.zenhub.com/files/430794588/850f007e-ebf6-43e0-9ee4-c597b0380c44/download](https://app.zenhub.com/files/430794588/850f007e-ebf6-43e0-9ee4-c597b0380c44/download)

**Comment by emmanurse** [comment]
See attached requirements[https://app.zenhub.com/files/430794588/850f007e-ebf6-43e0-9ee4-c597b0380c44/download](https://app.zenhub.com/files/430794588/850f007e-ebf6-43e0-9ee4-c597b0380c44/download)

**Comment by emmanurse** [comment]
See attached requirements[https://app.zenhub.com/files/430794588/850f007e-ebf6-43e0-9ee4-c597b0380c44/download](https://app.zenhub.com/files/430794588/850f007e-ebf6-43e0-9ee4-c597b0380c44/download)

**Comment by emmanurse** [comment]
Added updated requirements with mockups

**Comment by emmanurse** [comment]
![QA Card 104.png](https://images.zenhubusercontent.com/61aa40adae36b65ba0162435/2769f7af-3843-4252-b834-60feb522b84f)

**Comment by kbertodatti** [comment]
[https://app.zenhub.com/files/430794588/1b966ca8-e01b-4ac2-b460-09db02e1e799/download](https://app.zenhub.com/files/430794588/1b966ca8-e01b-4ac2-b460-09db02e1e799/download)

**Comment by emmanurse** [comment]
[https://app.zenhub.com/files/430794588/a395f0c4-d0c0-489b-9a92-bebff8b26283/download](https://app.zenhub.com/files/430794588/a395f0c4-d0c0-489b-9a92-bebff8b26283/download)

Included Dr. Dorr's feedback
