### ISSUE TITLE
Mock up add/save goal screen in provider app

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#138]
Screen mockup and requirements for "Add/save" goal in provider app.
* Add goal button
* Which fields need to be shown?
* Which fields are mandatory?
* Prompt/description text?
* Requirements for goal relationships (i.e., observation, target measures, condition)

![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/d4c4e450-2bee-4626-a354-e4f17117899d)

**Comment by emmanurse** [comment]
[Uploading... Card 118 Add Goal.docx]

**Comment by emmanurse** [comment]
[https://app.zenhub.com/files/430794588/72272581-f425-4397-9612-5dd2d9686896/download](https://app.zenhub.com/files/430794588/72272581-f425-4397-9612-5dd2d9686896/download)

**Comment by kbertodatti** [comment]
Google Drive: https://docs.google.com/document/d/1zLTr_L2wSA4q0l-wUoawA315DpCQjJ7P/edit?usp=sharing&ouid=114658391514455419481&rtpof=true&sd=true
