### ISSUE TITLE
Review and mock up Goals tab

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#139]
Review and redesign Goals tab in provider app
* incorporate target measures / last measure with goal into the predefined columns

https://docs.google.com/document/d/1jZLbc7NsHX3spyXdrf8g4SwlG2SCNmPG/edit

![image.png](https://images.zenhubusercontent.com/61aa40adae36b65ba0162435/c836ef5c-c17a-4d84-89aa-66b9a09001e3)

**Comment by emmanurse** [comment]
Moved "add goal button" requirement to card #138

**Comment by kbertodatti** [comment]
Google Drive: https://docs.google.com/document/d/1zLTr_L2wSA4q0l-wUoawA315DpCQjJ7P/edit?usp=sharing&ouid=114658391514455419481&rtpof=true&sd=true

**Comment by emmanurse** [comment]
Added link to requirements
