### ISSUE TITLE
Update read me for patient/caregiver app as needed

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#143]
Done criteria: Somebody can download and get code to build and run without extra help.
https://github.com/chronic-care/mycareplanner.git

**Comment by drbgfc** [comment]
Completed.
Please review and merge (if desired) the PR posted, here:
https://github.com/chronic-care/mycareplanner/pull/1

You will note that there are a few low priority TODO areas which I have specified that it may make sense to create tickets for and replace with the relevant data.

**Comment by drdavec** [comment]
Reviewed and merged.  We will add a short project/app intro as part of #147.
