### ISSUE TITLE
Review and mock up Health Maintenance & Interventions tab - Provider App

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#146]
Review and reorganize Interventions tab.
Requirements are here - https://docs.google.com/document/d/1RBlQMS7FGTqgJr8ppEOe0ue_yTD1v4yR/edit

**Comment by emmanurse** [comment]
![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/8341075c-b6a0-4659-acb8-5fd4af6f3973)
