### ISSUE TITLE
Add MyCarePlanner intro to read me

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#147]
Add brief introduction to project with focus on what is MyCarePlanner with link to AHRQ Confluence page.

https://github.com/chronic-care/mycareplanner

**Comment by kbertodatti** [comment]
From @savanahmueller : https://docs.google.com/document/d/1dN8rhl_v_-i_-z_WWlvLdf7d0XC2UGax7xjqaOIaSeA/edit

**Comment by kbertodatti** [comment]
@drdavec are you able to add the intro to github for us? The text is in the google link in the previous comment.

**Comment by drdavec** [comment]
Added the text into GitHub README, see:
https://github.com/chronic-care/mycareplanner/tree/develop

This is in 'develop' branch with other updates and will be merged into 'main' in the next release.
