### ISSUE TITLE
Add sample observation data for Patricia

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#151]
From #148

Add to sample data file.

Here's the data: https://docs.google.com/document/d/1DedAO1jYolb6_mJS3npryq5c1pQvZ_v1/edit

**Comment by swmuir** [comment]
updated https://meld.interop.community/CarePlanningQA/apps in Version 1.3 MCC Provider (azurecontainer)

**Comment by kbertodatti** [comment]
Open question: How to display EKG?

**Comment by kbertodatti** [comment]
QA questions:
* Not seeing "blood glucose" in Tests.
* Not seeing abdominal tenderness in Exam.
* No response in "Have you or any family members you live with been unable to get any of the following when it was really needed in past 1 year [PRAPARE]" in Questionnaires/Surveys section.

**Comment by kbertodatti** [comment]
QA questions/comments @swmuir:
* App is not launching in the Care Planning sandbox
* No data in Body Weight change over time table in Care Planning QA sandbox (used Vince provider)
* Still not seeing "blood glucose" in Tests (Is it under a different name)?
* Missing Sexual Orientation in History, but I do see Smoking Status.
