### ISSUE TITLE
Add content to Care Team tab

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#156]
Add FHIR query for CareTeams and populate the Team tab.

**Comment by drdavec** [comment]
![Screen Shot 2022-07-28 at 4.23.28 PM.png](https://images.zenhubusercontent.com/60109f68bc68dac2285387b1/79a0f898-8f8a-4333-b182-af33c2f4e63e)

**Comment by drdavec** [comment]
MyCarePlanner is now updated to include the Care Teams tab.  I added FHIR CareTeam query (which was missing), including query for references to team participant Practitioners.  This is available to test in MELD CarePlanning, QA, and Synthea8 sandboxes.  I also tested successfully with Epic sandbox.  And with Epic production endpoint (using my personal MyChart portal at University of Colorado Health.

Screenshot is from CarePlanning sandbox. Note that the 3rd team participant is an Organization reference.  I do not yet resolve and load Organization resources.  This could be added, but I don't think we'll ever see this in Epic pilot testing.

Finally, the care team participants do not include contact info (phone, email, address) from the Practitioner.  I can add this, but don't think we'll ever see contact info from Epic.  They specifically omit these details for patient-facing apps.

**Comment by kbertodatti** [comment]
* General practitioner - list this at the top.
* Remaining care team below.

**Comment by kbertodatti** [comment]
Per Eric: There are two types of care teams Epic can query. One is the longitudinal care team and the other is episodic (might be from inpatient care team from 4 years ago). Probably doesn't make sense to flatten all of these together.

Look at other resources that practitioners touched and use this to identify provider who should be closer to the top.
