### ISSUE TITLE
Add Activities tab populated with active ServiceRequests

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#157]
* Pull ServiceRequests
* Sort by descending order by recency

Data to show with ServiceRequests? Check if there's an option to go to Medline Plus.
Have limitations for procedure codes to make patient-friendly language.

**Comment by kbertodatti** [comment]
@swmuir to look at the queries for interventions tab in provider app. If they use Category, it's not going to work.

**Comment by drdavec** [comment]
Activities tab is completed and ready for QA.  Populated with all ServiceRequest with 'active' status, sorted in descending order by the 'start' date of occurrenceTiming (this is what appears to be populated in sample data from epic.fhir.com.

Use any of the patients in CarePlanning sandbox for testing.

Cannot find any ServiceRequest resources to test in Epic sandbox.

**Comment by kbertodatti** [comment]
This looks good. Did you look into the option to link to Medline Plus for the procedure codes?
