### ISSUE TITLE
Review/update Patricia Noelle Connectathon sample data

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#16]
Create second profile for Patricia Noelle to support Con 29 testing

1) Identify value sets needed for Connectathon 29 - Emma
2) Correct as needed

**Comment by emmanurse** [comment]
1. Handle data duplication 
2. Handle recurrent data

**Comment by kbertodatti** [comment]
Dave will create separate files for different parts of Patricia's data; Emma can then edit data in file to add into her full profile.

**Comment by kbertodatti** [comment]
Dave uploaded SDOH data for Connectathon 29 scenarios; loaded into server.
