### ISSUE TITLE
Create common data services for vital signs

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#162]
- Extract vital signs for blood pressure from both patient and provider app.
- Look for common functions.
- Create these into common data service API.
- Create this as a branch in the provider app repo.

How do we QA this?
* start with provider app; modify locally.

**Comment by svalluripalli** [comment]
Added initial project to git repository with basic attributes in VitialSigns Observation, to get Blood pressure information: https://github.com/chronic-care/eCareCommonDataServices
