### ISSUE TITLE
Mapping for Condition Resource

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#201]
Need to map from Condition resource to view. Classification piece will be done separately from the mapping.
Provider app

From Dave: focus on the JavaScript mapping only for the provider app at this time. We'll continue using CQL for mapping to view models in the patient app.

**Comment by svalluripalli** [comment]
Completed Development work.

**Comment by savanahmueller** [comment]
Use stand up on 11/3 for Sai to demo

**Comment by savanahmueller** [comment]
Sai pushed latest code yesterday. Sean is reviewing.
