### ISSUE TITLE
Mapping for Goal Resource

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#212]
Application-level mapping for Goal Resource in provider app.

**Comment by savanahmueller** [comment]
Provider app initially not leveraging Javascript "PROMISE".
Need to update MCC provider accordingly.

**Comment by kbertodatti** [comment]
Figure out if calculation is required for eGFR. If it is, then we would need a new card to build this for the patient/caregiver app. If no calculation is needed, just reference the lab value (updated LOINC code, most likely) directly.
