### ISSUE TITLE
Allow for multiple logins

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#214]
Does not include data aggregation.
Use local storage implementation to save current state and an array of states and use that information to allow for multiple logins.
This is just a basic connection of local storage to using the tokens.

Sequence of cards:
#214
#217
#215
#240

**Comment by savanahmueller** [comment]
Q from Dan: Find out if there is a concrete deadline. Assuming before end of soft-go-live, before formal patient testing. Dave will follow up.

**Comment by drbgfc** [comment]
Is there a reason this is open, shouldn't it be closed?
