### ISSUE TITLE
Create additional sandboxes in MELD

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#216]
* Staging
* Testing
* Development
* MCC Primary EHR sandbox
* MCC SNF sandbox

Add Karen and Dave as admin.

**Comment by savanahmueller** [comment]
Dan is working on this through

**Comment by savanahmueller** [comment]
Step 2: coordinate with OHSU and RTI to create meaningful set of data. 
We have no example of same person across different EHR systems.

**Comment by kbertodatti** [comment]
@swmuir invite Karen to sandboxes and Karen will invite everyone else.

**Comment by kbertodatti** [comment]
@kbertodatti to test Develop and Testing sandboxes.

@swmuir noticed that both the apps had some problems with data he imported from Matt's export of Patricia Noelle.

**Comment by savanahmueller** [comment]
Will likely need another card to populate sandboxes.

**Comment by kbertodatti** [comment]
Added #105 to populate sandboxes
