### ISSUE TITLE
As a patient, I don't want to re-select to the health system EHR that I used to launch the MyCarePlanner when I choose to connect to additional health systems.

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#217]
As a patient, I don't want to re-select to the health system EHR that I used to launch the MyCarePlanner when I choose to connect to additional health systems.

**Comment by kbertodatti** [comment]
Maybe @swmuir or @svalluripalli can work on a separate branch for the UI screens.
- Display endpoints that have been connected (radio check-boxes to reconnect).
- UI to select other providers. Maybe a second section as part of the same submit to select multiple providers. Same component can be used on startup once completed?

Need mockups first.

**Comment by kbertodatti** [comment]
Karen to work with Lucas on what the flow should be when launching app with the intention to connect to more than one health system.

**Comment by kbertodatti** [comment]
Dan: Some concern if somebody hits refresh for the launcher to change.

**Comment by savanahmueller** [comment]
Dave will do first pass and deploy to sandbox for Karen/Savanah to QA
