### ISSUE TITLE
Explore how to update Common Data Services to support multiple FHIR endpoints

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#226]
For patient app, focus on FHIR data services functions, APIs and performance.  Unit test and integrate only the FHIR servicers into the My Care Planning by next March.  OHSU will be starting some initial testing with production data in about January, which may raise issues related to performance or integration.  And they are still in early stages with design for a secondary FHIR data store and approach to write aggregated data from patient app into their research data store.  We will need to expand or refine FHIR services to support this, but their design is not yet ready for us to implement.

**Comment by savanahmueller** [comment]
Sai is documenting and will discuss with Sean on 01/06

**Comment by kbertodatti** [comment]
Sean worked wtih Dan to create a structure that maintains provenance. Now just need to execute (reference #239).
