### ISSUE TITLE
Resolve warning in the console

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#228]
index.js:1420 Warning: Failed prop type: MUI: Combining `elevation={3}` with `variant="outlined"` has no effect. Either use `elevation={0}` or use a different `variant`.
    in ForwardRef(Paper) (at App.tsx:110)
    in App (created by Context.Consumer)
    in Route (at src/index.js:14)
    in Switch (at src/index.js:12)
    in Router (created by BrowserRouter)
    in BrowserRouter (at src/index.js:11)
    in StrictMode (at src/index.js:10)

**Comment by kbertodatti** [comment]
@svalluripalli can you look into fixing this bug? Do a pull request for @drbgfc to review.

**Comment by savanahmueller** [comment]
Sai to confirm this error is no longer there.
