### ISSUE TITLE
Generalize app data structure for aggregating and updating FHIR data

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#237]
Need an API or data structure to adding, removing, and updating FHIR data individually.
Right now, all we can do is overwrite the entire set of all arrays; can't even separate into resources.
Should allow for incremental loading.

Step 1: Decide what the implementation is going to be. What design choice are we going to use for this API.
Step 2: Develop the data that will be within it.

Question:
- Do we have separate arrays per provider? If we put all into one array, the only way to know where the data came from is by provenance.

**Comment by kbertodatti** [comment]
@swmuir to start with a design paper and share with Dave, Dan, and Sai for review.

**Comment by savanahmueller** [comment]
Sean touched based with Dan on the design and it is ready for implementation. Will open a new card for the implementation.
