### ISSUE TITLE
Update UI to support multiple providers

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#240]
Update UI to support multiple providers using aggregated data. 
Order of cards: 
#240 (THIS ticket, UI only)
#215 (Data aggregation for multiple logins)
#239 (Implement aggregation of patient data in the patient app - assigned to Sean, is this a duplicate of 215? Is Sean working on this? Should it be listed in this ticket?)

What is the MVP we want for flow? - successfully retrieve data from two providers and display it.
Baseline:
1. Launcher
2. select a provider in the provider component so that there are multiple logins
<Data aggregation for multiple logins#215>
3. aggregate the data within the app
4. process each provider data set using CQL and then display the aggregated CQL results

*Shouldn't this non-MVP be a separate, future ticket?
Next steps
1. Launcher
2. Prompt to Re-login to other providers if previously visited (based on what is in local storage)
3. If no previous provider, no prompt is required at this time
4. If patient chooses provider list from link from home page, they can do multiple logins.

Start with 4 and then reuse that component in a prompt. 

If authorizations are still valid, it should read all data from all active tokens. (issue with time loading)

For MVP, when authorizations are valid, load the most recent provider and allow patient to choose more. 
*next steps, can show what is already authorized and reload would be quicker

**Comment by drbgfc** [comment]
Completed in the sense that the UI is capable now. Update in dev allows selection of one or more providers. At this time I have disabled more than one until aggregation is implemented. But, the mulit option can loop through all selected, but will only display/overwrite with the final one.

*Should probably break out the 2nd half (non-MVP) and prioritize into another ticket
