### ISSUE TITLE
Fix provider app without Java dependencies

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#246]

**Comment by kbertodatti** [comment]
Sean update on testing software: lambda test (uses no code language testing; can set up regression test).

**Comment by savanahmueller** [comment]
Completed beta testing - 4/13
QA task for R release testing by Savanah/Karen

**Comment by kbertodatti** [comment]
Feedback from QA:

**Top bar**
- v2.0 doesn't expand.

**Goals tab**
- v2.0 is still using the "old" Goals layout. Specifically, columns for Goals should only have: Priority, Goal, Target Date, Achievement Status, Most Recent Result, Expressed By.
- v2.0 should NOT have the "Target Laboratory/Clinical Values" separate from the Goals table. We created the new column in Goals table for "Most Recent Result" which includes Target and Last Value (value and date).
![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/ba86b737-c5b5-4b16-9151-3f38ae6473db)
- Popup "Goal Details" window does not show all the data compared to v1.3. Also cannot close the "Goal Details" window after opening it.
![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/b3de0cf7-959c-4d74-b2e2-133abf14cbd5)

**Health Concerns tab**
- In v2.0 Popup for Active Diagnoses is blank.
- In v2.0 Popup doesn't close when you click "Close"
- Not sure if this is intentional, but under the "Health Concerns" category v2.0 shows "Unemployed" and "Unable to drive a car" and v1.3 shows "Rash". I think v2.0 is right, but if the apps are using the same sample data...why is it pulling different things?

**Health Maintenance & Interventions tab**
- v2.0 is showing the "old" layout (separate tables for Active Medications, Education, Counseling, and Referrals) whereas v1.3 is showing the new layout (two tables: one for "Active Medications" and one for "Active Orders").
- v2.0 has same issue with pop-up for Active Medications details. It doesn't populate with the same info and the pop-up doesn't close when you click "Close".

**Health Status Evaluation & Outcomes tab**
- v2.0 shows some values that are slightly different from v1.3. For example: Under Exam, v2.0 states "Knowledge level of diet regime (observable entity)" while v1.0 states "Limited knowledge level of diet regime." Another example is under Questionaires/Surveys, for "Pain Enjoyment General Activity (PEG) Assessment", v2.0 result says "7, 5, 4" but v1.3 says "5". In the same category, the Result for "Have you or any family members you live with..." for v1.3 is blank, but in v2.0 it says "Clothing,Child care."
- There are no tests/results showing for "Procedure Results" "History" Imaging Results" and "Therapy" in v2.0 but there are for v1.0.

**Care Team tab**
- v2.0 is blank for Care Team whereas v1.3 has 2 entries (Patricia and Dr. Carlson).
![image.png](https://images.zenhubusercontent.com/6197ef7a2c4a0098cd7694e6/d414c95c-0fc6-47e9-a11c-f62b0c68ef85)

**Comment by savanahmueller** [comment]
QA for Provider 2.0 app:
(V2.0 is on the LEFT)
General notes: As Karen noted, there were some data discrepancies where it didn't seem like it was pulling from the same source. 
Top bar:
Both versions say Careplan v1.2.6 - Beta. Should v2.0 be updated to say v2.0?
The v2.0 patient bar does expand, but not by clicking the down arrow. Instead, you need to click the folder, a small, empty, white box opens, and then you can click there, expanding the patient info bar. The 2.0 patient bar is more populated than 1.3. Once open, you cannot minimize. 
![Screenshot 2023-04-20 161704.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/c92a111d-353c-449d-9e31-5de41fd2e811)

Goals:
2.0 has additional fields including addresses, status, created, accepted by, type. Note, can "type" have a different same like "author type" or "author role"? Type seems too generic. 

![Screenshot 2023-04-20 161214.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/86f91fb7-b300-4402-aa2e-42316b636965)
![Screenshot 2023-04-20 161034.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/7ed74db2-6582-41da-bba4-62992ad0948d)

Health Concerns:
2.0 has a discrepancy from 1.3. Also does not pull any "health concerns" only diagnoses. 
The links to switch to a different tab under CKD both work for me.
![Screenshot 2023-04-20 161056.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/63651948-c6db-495b-a390-6f1bfe219a44)

Health Maintenance & Interventions: 
v2.0 has 4 tables but only one is populating (active medications)
v1.3 has 2 tables with both populated (active medications, active orders)
![Screenshot 2023-04-20 161111.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/9a19e87f-b167-4f3f-96da-daebaaa53c48)

Health Status Evaluation and Outcomes:
v2.0 no longer has the Pain Severity and PHQ9 score buy the graphs, but I could not find them anywhere else. 
v2.0 under tests, the first test is blank, although there is a result and a date. 
The change in eGRF, there is a drop down but nothing to select. 
Dates are different for UACR, A1C, Serum phosphorus, LDL, HDL, triglycerides. 
Questionnaires/surveys are in a different order. 
v2.0 is no longer pulling procedure results, history, imaging results, or therapy. 
![Screenshot 2023-04-20 161133.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/55efc117-a812-4939-bfd3-d20364603fd2)
![Screenshot 2023-04-20 161152.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/e1d39c4b-f47f-4667-9f02-571f627e7337)
![Screenshot 2023-04-20 161214.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/2f95663b-fb9f-4e9f-a0ef-572a282c1c98)

Care team: 
No care team is populated for v2.0
![image.png](https://images.zenhubusercontent.com/61b8c8b30aba1114f9de2b8d/e18b5a34-dcad-4277-ad0c-ccde44894ea3)
