### ISSUE TITLE
Design UI flow/wireframes to approve saving data into SDS

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#264]
"Share my data from other providers with OHSU"

https://www.figma.com/file/28Tvzsvn9S9wEYCQvmzfUT/MCC-eCare-Patient%2FCG?type=design&node-id=223%3A3042&mode=design&t=fgKCEa9guDxUOw7Z-1

**Comment by NotAnotherDoorNob** [comment]
Here is the most up to date figma link https://www.figma.com/file/28Tvzsvn9S9wEYCQvmzfUT/MCC-eCare-Patient%2FCG?type=design&node-id=223%3A3042&mode=design&t=fgKCEa9guDxUOw7Z-1
