### ISSUE TITLE
Import ndJSON into MELD sandbox.

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#267]
Load FHIR bulk data for Patricia Noelle export from OHSU into MELD
Matt is working on exporting Patricia Noelle

There are some tools that transform ndJSON into a FHIR bundle.

**Comment by kbertodatti** [comment]
@drdavec to dig up the attachment from Matt.

**Comment by kbertodatti** [comment]
Put this in "MCC OHSU sandbox".

Sandbox list:
1. MCC Staging - our patricia noelle
2. MCC Testing - our patricia noelle
3. MCC Development
4. MCC OHSU Sandbox - OHSU's patricia noelle
5. MCC SNF Sandbox - OHSU's patricia noelle

**Comment by kbertodatti** [comment]
@swmuir found a technical issue with their data. Pinged Matt who said that it was everything in their export. There were some references to specimen and location that wasn't included in the data output.
The IDs also had an issue. Sean wrote a script to clean up the IDs. We can rerun the script and run a brand new set of IDs (can restart without deleting sandbox).
