### ISSUE TITLE
Add progress indication for non-redirect non-reauthorization to a prior endpoint

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#275]

**Comment by drbgfc** [comment]
Prior to this, the application would only show the old data from the last endpoint until the new data was loaded an overwrote. There was no indication that loading was happening.

**Comment by drbgfc** [comment]
Going to move to done I have tested and the tests that were done by others already happened after the implementation. So,  others wouldn't know what it would have looked like (no loading indication) prior, anyway.
If anyone disagrees, feel free to move it back. Thanks.
