### ISSUE TITLE
Convert indeterminate progress indicator to Determinate in patient app (in addition to existing text)

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#278]
-Progress indication (vs continuous load) via an incremental progress bar tied to each task (it will only be an estimate, as each task can take any amount of time depending on patient records)
-Display of how many items have been completed overall, in realtime (what step we are in, or how many are left), again, these are estimates. Or, could be more specific, like count of resources loaded, like Dave mentioned (I think this is what you meant, vs a total at the end), in realtime. It's basically a count of each step that's relevant. e.g. if we have loaded Medication and LabResult so far then # or resources loaded would display 2, then Social History is loaded and it updates to 3

**Comment by drbgfc** [comment]
It might make sense to do this before and/or in conjuction with #274. IF we can see the incremental loading in the progress bar, we can see how it lines up with what is actually displayed in realtime as well. Would help with testing anyway.

**Comment by drbgfc** [comment]
1/2 done and in develop (pushed update for the 1st item, Support determinate progress indication

**Comment by drbgfc** [comment]
Fully complete now: Pushed Support for resources loaded count (if fetched only, not just a count of requested resources) in progress ind

**Comment by savanahmueller** [comment]
QA testing done using this [link](https://chronic-care.github.io/mycareplanner/launch.html?iss=https://gw.interop.community/CarePlanning/data). Looks great. Worked for all 3 patients and the caregiver proxy. Indicated the time of day each item loaded and how many resources were pulled as well as % of progress. Progress indicator bar is only on the home page, not the other tabs--which is okay, just pointing out.
