### ISSUE TITLE
Expand patient app logging for tab usage

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#290]
Have a log entry each time one of the tabs is visited.
Also log the number of resources read for each query.

**Comment by savanahmueller** [comment]
Have a log entry each time one of the tabs is visited.

**Comment by savanahmueller** [comment]
Add to agenda for OHSU and RTI on 6/14

**Comment by savanahmueller** [comment]
Matt sent back Header requirements. 
Sai is working on building the docker. 
Sean and Sai will work with Matt on this issue.

**Comment by drdavec** [comment]
Here are additional details on logging received today from RTI/OHSU:

Log files will contain, at a minimum, the following:

A record of any errors encountered
The time stamp for each query run
The time stamp for each query return
The number of resources returned for each query 
The time stamp when a user enters a tab
The time stamp when a user exits a tab
A unique session ID that allows these events to be understood in the context of each other

 

Table 5.        Log File Data Details

Data Element

	

Description

	

Summary




ID

	

Unique ID for a given session

	

Numeric session ID




d/t

	

A record of any errors encountered and their type

	

Error type




d/t

	

Details on query request

	

Query request type




d/t, ct

	

Details on query response including number of resources returned for each query type

	

Query response type, number of resources returned




d/t

	

Details on participant accessing an application tab

	

Tab open




d/t

	

Details on participant accessing an application tab

	

Tab close

ct = count; d/t = date/time stamp; ID = ID or unique identifier.

**Comment by kbertodatti** [comment]
@sravandigitalhie can you write out a bullet list of exactly what is being logged?

**Comment by sravandigitalhie** [comment]
Fields that show in app logging:
- The timestamp for each query run
- The number of resources returned for each query
- The timestamp when a user enters a tab
- A unique session ID that allows these events to be understood in the context of each other
- A record of any errors encountered

**Comment by savanahmueller** [comment]
Response from Matt. Not seeing updated logging. 
@swmuir and @sravandigitalhie will connect through slack

**Comment by kbertodatti** [comment]
Update from Matt via Sean: Matt was able to change some configurations and is now able to run the logging. Matt has accepted it.
