### ISSUE TITLE
Add UI display of selected providers

### ISSUE THREAD

**Issue by savanahmueller** [chronic-care/mcc-project#305]

**Comment by savanahmueller** [comment]
Reference #240

Next steps

Launcher
Prompt to Re-login to other providers if previously visited (based on what is in local storage)
If no previous provider, no prompt is required at this time
If patient chooses provider list from link from home page, they can do multiple logins.
Start with 4 and then reuse that component in a prompt.

If authorizations are still valid, it should read all data from all active tokens. (issue with time loading)

For MVP, when authorizations are valid, load the most recent provider and allow patient to choose more.
*next steps, can show what is already authorized and reload would be quicker

**Comment by kbertodatti** [comment]
@drdavec isn't this one done?

**Comment by drdavec** [comment]
App does not cover #2, to prompt for previously visited providers.  But maybe we create a new card for this.  Now, user must reselect multiple providers from full list each time app is run.

**Comment by kbertodatti** [comment]
Makes sense to me. I'll move this to done and make a new card for #2.

**Comment by drdavec** [comment]
Although, this remaining enhancement looks the same as #217, in Ready for Dev?

**Comment by kbertodatti** [comment]
I think you're right. I'll move this card to done and clarify the description in #217.
