### ISSUE TITLE
Display source for health systems that do not return provenance (i.e., the VA)

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#317]
Two possible ways to consider:

1.  In our health system EHR list, we have a name associated with each endpoint.
2.  Look at capabilities statement for those endpoints and see if there's an organization name in the metadata that we can pull out.

**Comment by kbertodatti** [comment]
Check if this was addressed by Sean already in #315

**Comment by savanahmueller** [comment]
Want resources to be sorted. 
@swmuir to share branch with @drbgfc

**Comment by kbertodatti** [comment]
This was addressed in #316. Will QA this through that card.
