### ISSUE TITLE
Set up an Epic sandbox client for the clinician app

### ISSUE THREAD

**Issue by swmuir** [chronic-care/mcc-project#323]
This sandbox is for testing purposes to help make sure our apps work for Epic since there has been issues launching with OHSU Epic in the past.

**Comment by savanahmueller** [comment]
Coordinate with Noah to start around 11/20

**Comment by kbertodatti** [comment]
Schedule time for Noah and Sean to set this up week of Nov 27.

**Comment by kbertodatti** [comment]
Issue: When Sean logs in, it uses DSTU2 even though it's supposed to be R4. Sean will continue tinkering.

**Comment by kbertodatti** [comment]
Have a potential fix from Matt. Still in progress, not blocked.
