### ISSUE TITLE
Create toggle function to turn on/off logging service

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#325]

**Comment by drbgfc** [comment]
FYI: This is really just done through new env vars on build. No new function was needed. It is not a dynamic/live toggle. If we want a dynamic/live version that can certainly be implemented  by adding a state to control it and a UI toggle switch. I'm assuming we don't have a need, though.

As is,:
Added disable log service and event log options. To use, configure in env.local:
REACT_APP_LOG_ENABLED=true or false
REACT_APP_LOG_EVENTS=true or false
By default, both are set to true, as that's how it was, and will likely be in production

**Comment by savanahmueller** [comment]
Sravan confirmed working.
