### ISSUE TITLE
Update configuration for the available endpoints

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#328]
Design a configuration for the available endpoints that presents the user with a searchable list of endpoints to connect to.

Reference #316.

**Comment by savanahmueller** [comment]
<img width="1244" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWtrQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--11f3680ffbe8180d65f10cca3883e777501a3b93/image.png" alt="image.png" />
Sean confirmed with Dan and Dave on 2/2/24.

**Comment by kbertodatti** [comment]
@swmuir has question for @drdavec on github and how we want to manage some things. Should be done by COB 3/1.
