### ISSUE TITLE
Bottom navigation icon turns white when selected

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#334]
<img width="573" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd2FnQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--964a463e45e95d8777c0ec7af6949b6101c95aa7/image.png" alt="image.png" />

**Comment by sravandigitalhie** [comment]
For Home:
<img width="522" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmY5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--82172943edfa081c3efe9ed07a91c19147ed64de/image.png" alt="image.png" />

For Care plan:
<img width="529" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnI5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3b4b3640073f604c8ef410de356a138c7ad0cb06/image.png" alt="image.png" />

For Health status:
<img width="547" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNlg5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bafdb34194549d547a39fa6b017ebe6ca04f4108/image.png" alt="image.png" />
For Team:
<img width="524" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNnY5QXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62c6c4e0052524117c5d5cca3109432d5f3099b2/image.png" alt="image.png" />
