### ISSUE TITLE
eCarePlanner 3.1.1 - Patient ID not displayed

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#345]
Patient ID is not displayed:

![image](https://github.com/chronic-care/mcc-project/assets/979938/5c67a92f-58f5-491f-90d1-c6cfaed5dbcd)

**Comment by kbertodatti** [comment]
@swmuir to ask matt for the specific patient.

**Comment by kbertodatti** [comment]
Being addressed with #349

**Comment by kbertodatti** [comment]
Remove all the crossed out fields and everything "under the fold". Move Race/Ethnicity into the place where Patient ID currently is.

<img width="1223" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBempMQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b600411afe63686f7cbb17b7bd57dbccc71c47b0/image.png" alt="image.png" />
