### ISSUE TITLE
eCarePlanner 3.1.1 - no goals displayed

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#347]
goals seems to be operating weirdly.  Christina reported that the Goals section "just spins":

![image](https://github.com/chronic-care/mcc-project/assets/979938/4e04a49d-8e5a-4f85-bb9c-b0dc603366ed)

but I see that it appears to complete (no spinner), it's just empty:

![image](https://github.com/chronic-care/mcc-project/assets/979938/b30dea16-5097-4c2d-a390-accdd91835b8)

here's what's displayed for this patient in the MyCarePlanner app:

![image](https://github.com/chronic-care/mcc-project/assets/979938/5463312d-a745-4fdc-bf3d-aaeeb971e7b8)

It also appears that there aren't any errors related to getting the goals, although I do see 405 errors in _log-service.ts_ that occur after `getSummaryGoals` calls.  I suspect these 405 errors may be related to #346 but I can't be sure.

![image](https://github.com/chronic-care/mcc-project/assets/979938/631738c1-775e-4fb8-8eae-ce81c956da5d)

**Comment by kbertodatti** [comment]
Keep this card (close #342 as duplicate).
