### ISSUE TITLE
eCarePlanner 3.1.1 - no option to select eGFR dataset

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#348]
There are supposed to be datasets displayed here for user selection, but this dropdown is blank:

![image](https://github.com/chronic-care/mcc-project/assets/979938/7a28ab5f-9cdb-4e53-8141-eba3fa432655)

**Comment by swmuir** [comment]
Removed per design

**Comment by kbertodatti** [comment]
eGFR is calculated from 2 other labs. The formula that was used included a variable for black/not-black which introduces a racial bias. Look at LOINC codes and what's being returned by labs.

Jacqueline to ask Michelle and/or Dr. Dorr.
