### ISSUE TITLE
eCarePlanner 3.1.1 - Care Team data not populated

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#349]
in eCarePlanner 3.1.1, we see the following under Care Team:

![image](https://github.com/chronic-care/mcc-project/assets/979938/11a9d01b-b557-413d-9355-9710c0fa3f64)

whereas this is what's displayed in MyCarePlanner:

![image](https://github.com/chronic-care/mcc-project/assets/979938/cbd9d210-e046-489d-893b-3c9540b7af89)

of note, there are no browser console logs that contain the term "careteam" which makes me think the app is just missing code to populate this section, as you can see by my browser console logs, filtered by the term "careteam":

![image](https://github.com/chronic-care/mcc-project/assets/979938/4625a3d5-80dc-434b-912c-d35ce9b38521)

**Comment by kbertodatti** [comment]
@drdavec can you specify the logic of what's pulled in the care team tab on MyCarePlanner?

@swmuir to investigate current logic in eCarePlanner.

**Comment by drdavec** [comment]
MyCarePlanner reads all CareTeam resources for a patient, where category = 'longitudinal'
CareTeam?category=longitudinal

For Epic, this is described here as their USCDI conformance support for CareTeam:
https://fhir.epic.com/Specifications?api=1069

MyCarePlanner then displays all members of the returned CareTeam(s)

In addition, MyCarePlanner reads Patient.generalPractitioner, and if populated by the EHR, will display this Practitioner name as the patient's Primary Care Provider, shown at the top of the Care Team tab.

**Comment by kbertodatti** [comment]
@swmuir remove all the crossed out fields and everything "under the fold". Move Race/Ethnicity into the place where Patient ID currently is.

<img width="1221" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBd1ZaQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b4373b39e12c3bc2e25f3ad28e6f47375c91cddf/image.png" alt="image.png" />
