### ISSUE TITLE
eCarePlanner 3.1.1 - it appears hardcoded spaces are being appended to "category" parameters, breaking calls

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#351]
while putting together issue #350, I noticed that the calls that are failing include the following interesting bits in their OutcomeResponse diagnostics:

![image](https://github.com/chronic-care/mcc-project/assets/979938/930142b0-eb5d-4bc4-852d-e30fa82bcc80)

Why are these spaces here?

Checking in the call that's actually made and that triggers the error, I see it appears that spaces are getting appended to these parameters which is probably why this - and like half a dozen other calls - are failing (note the "category=imaging++++" parameter, those plus signs shouldn't be there):

https://epicmobile.ohsu.edu/FHIRDEV/api/FHIR/R4/Observation?category=imaging++++&_sort=&patient=eFTHaVbQzCEwOEE97maN2MC2jJi-r8nnkhRh.umMUlz03

This sort of issue is evidenced on each of the following calls.

![image](https://github.com/chronic-care/mcc-project/assets/979938/dc05bb77-2b53-42bc-8d96-b083a9f92f98)

Suggest to trim the "category" parameter before including it in the URL.

**Comment by kbertodatti** [comment]
Investigate together with #350

**Comment by swmuir** [comment]
This response is from the server 
modified category to invalid
xxxxxxxxxxxxxxxx
 EccDS: getObservationsByCategory - start with category - xxxxxxxxxxxxxxxx - undefined undefined
This is the client level logging

We use the ones below 

https://www.hl7.org/fhir/valueset-observation-category.html


Does everyone of the above value set return the issue ?

**Comment by swmuir** [comment]
@mattStorer - Please see above comment thanks Sean

**Comment by mattStorer** [comment]
spoke with Sean about this over email, tracking here for visibility.

issue relates to how `queryString` is being defined in _observation.ts_, in which the string continues for several lines and contains spaces that appear to be there for formatting, but because the string isn't closed, those strings get roped into the variable as literals.

![image](https://github.com/chronic-care/mcc-project/assets/979938/b47beb2e-6704-49d7-88a0-d62483cbaab4)

https://github.com/chronic-care/e-care-common-data-services/blob/bea2448c343c2b9dbc655bbadef228392b80d4b4/source/lib/observation/observation.ts#L177-L181

the easiest solution is to remove the formatting and run everything together so it's all on one line, e.g.:

```
const queryPath = `Observation?category=${category}${sortType ? `&_sort=${sortType}` : ''}${max ? `&_count=${max}` : ''}${date ? `&date=${date}` : ''}`
```

it was also noted that `sortType` was being checked for presence, but not being included in the positive-case result string after `&_sort=`.  the solution code above includes this fix as well.

**Comment by swmuir** [comment]
Modified the query add logging to show the result has no spaces

**Comment by mattStorer** [comment]
verified spaces removed from _category_ parameter in 3.1.2 and working:

![image](https://github.com/chronic-care/mcc-project/assets/979938/c8797370-77dd-428e-8f79-61f4e6417a1d)
