### ISSUE TITLE
MyCarePlanner : "PKCE code challenge is required by the application" error during VA connect attempt

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#353]
I'm testing out the VA sandbox integration with the latest MyCarePlanner build, and I'm encountering this error:

`invalid_request: PKCE code challenge is required by the application.`

I have verified that the client ID and redirect URI are correct.

Does MyCarePlanner perform a PKCE authorization?  See this link for details:

https://developer.va.gov/explore/api/patient-health/authorization-code#pkce-authorization

**Comment by mattStorer** [comment]
adding `"pkceMode": "unsafeV1"` to the _myproviders.json_ `config` block for the VA sandbox entry fixed the problem

**Comment by xmlmodeling** [comment]
My MyCarePlanner does support PKCE.  But it seems that this setting was
lost as part of migrating to the provider configuration file.  Our previous
launch.js file included this config:

    {
// VA sandbox
issMatch: "https://sandbox-api.va.gov/services/fhir/v0/r4",
redirectUri: "./index.html",
clientId: process.env.REACT_APP_CLIENT_ID_va,
scope: process.env.REACT_APP_VA_SANDBOX_ENDPOINT_SCOPE,
pkceMode: "unsafeV1"
// "unsafeV1" - Use against Smart v1 servers. Smart v1 does not define
conformance, so validate your server supports PKCE before using this setting
},

Thanks,
  Dave
