### ISSUE TITLE
MyCarePlanner - should "Add new goal" link be displaying here?

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#355]
In the latest MyCarePlanner app, I have it configured to hit the SDS with the following environment variables set:

`--env REACT_APP_SHARED_DATA_ENDPOINT="https://sds-mccecare-dev.ohsu.edu/fhir" --env REACT_APP_SHARED_DATA_AUTH_ENDPOINT="https://epicmobile.ohsu.edu/FHIRDEV/api/FHIR/R4" --env REACT_APP_SHARED_DATA_SCOPE="launch/patient openid fhirUser patient/*.read patient/*.write"`

But in the Goals tab, I don't see a way to create a new Goal:

![image](https://github.com/chronic-care/mcc-project/assets/979938/5ec82dc7-efc8-472b-9625-1ee81dc47a35)

I seem to recall this existing here, did it move?

**Comment by mattStorer** [comment]
also I just tested creating a new _QuestionnaireResponse_ which, at the end, attempting to save it, it doesn't look like it interacted with the SDS as I saw no logs generated by it

**Comment by mattStorer** [comment]
it seems this "Add new Goal" link isn't showing up here because I wasn't including a `REACT_APP_SHARED_DATA_CLIENT_ID` environment variable, which is new, and its absence was causing the app to think that the SDS isn't configured.

The SDS doesn't employ client IDs, as that is a part of the SMART-on-FHIR infrastructure, which the SDS doesn't employ.

In subsequent testing with Sean to get SDS integration working in the latest release, it seems that MyCarePlanner attempts to perform a SMART-on-FHIR authentication against the SDS as soon as the app launches.  Evidently EMI has been using Meld as a stand-in for the SDS in testing, which does use SMART-on-FHIR, and I think perhaps that is why the app may have been constructed to do this.

So this issue points to perhaps a bigger issue, which relates to how MyCarePlanner is attempting to configure its connection to the SDS.  It should not be using SMART-on-FHIR authentication, it should be using the _access_token_ from the initial OHSU authentication that launches the app.

**Comment by xmlmodeling** [comment]
No, the CLIENT_ID is not needed and should not be used in OHSU's
environment. This is intended for use (preliminary testing by us) for an
SDS that has it's own login credentials and authorization separate from the
EHR.  Not needed by you.

Thanks,
  Dave

**Comment by xmlmodeling** [comment]
In your setting for REACT_APP_SHARED_DATA_AUTH_ENDPOINT, is this
**exactly** the same base URL being used to launch the app by users in your
environment?  This is used (not the client_id) to look up an existing
OAuth2 access token from a prior login that can be used for accessing the
SDS.  That is also what determines display of the Add New Goal option, so
it seems that the SDS config to find a shared access token is not working.

Thanks,
  Dave

**Comment by mattStorer** [comment]
@xmlmodeling Yes, the `REACT_APP_SHARED_DATA_AUTH_ENDPOINT` is the same as it's ever been, defined as such:

`--env REACT_APP_SHARED_DATA_AUTH_ENDPOINT="https://epicmobile.ohsu.edu/FHIRDEV/api/FHIR/R4" \`

Of note, with the most recent release received from EMI that contained additional debug logging, it seems that things are functionally working better, that MyCarePlanner at least recognizes that the SDS exists and tries to make calls to it (which fail, but that's a separate thing).  Also, the "Add a New Goal" link is now displaying:

![image](https://github.com/chronic-care/mcc-project/assets/979938/bef7cdce-25da-4d82-9e0f-66faffcb94c9)

It's not clear why ostensibly adding just debug logging would make things work.  I didn't change any configuration settings.  Doesn't matter, we're making progress, that's what matters.

**Comment by kbertodatti** [comment]
In summary: If the SDS is there, then add new goal will be there. If not, it won't. This is not a bug.
