### ISSUE TITLE
MyCarePlanner - display version info

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#356]
The latest MyCarePlanner release doesn't display any version information in its user interface, which potentially contributes to confusion.

Could current version info be displayed somewhere unobtrusive but prominent so it's easy to identify when using the app?

I'm thinking this would be a good spot to put it:

![image](https://github.com/chronic-care/mcc-project/assets/979938/2cd8127b-d193-42a1-987d-490f08d11bed)

___
Automate this as part of the build process (look into environment variable in the .env file). Can also make this a global variable and figure out how to automate this.

**Comment by kbertodatti** [comment]
Added another variable REACT_APP_VERSION, this holds the value of the version for the release.
