### ISSUE TITLE
MyCarePlanner - validateDOMNesting warning - <h5> cannot apear as a descendant of <p>

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#357]
Minor thing, but I wanted to log it for tracking.

It looks like MyCarePlanner's UI is trying to embed an HTML header tag within an HTML paragraph tag, which is creating some verbose warnings in the console.

Probably a super easy thing to fix.

![image](https://github.com/chronic-care/mcc-project/assets/979938/25d4457c-dc60-4a0f-ac70-16ec5b0dd9a9)

**Comment by drbgfc** [comment]
That's correct, here is the code from Home - 2 examples. Easy fix. Thanks:

```
            <div>
             
                <p>
                  <h5 style={{ paddingTop: '20px' }}>Shared Health Records</h5>
                  <Link to={{ pathname: '/provider-login', state: { fhirDataCollection: this.props.fhirDataCollection } }}>Retrieve records from additional healthcare providers</Link>
                </p>
             
            </div>
 

            <div>
              {typeof sdsurl !== 'undefined' ? (
                <p>
                  <h5 style={{ paddingTop: '20px' }}>Share your health data</h5>
                  <Link to={{ pathname: '/share-data' }}>Share your health data</Link></p>
              ) : (<p></p>)}
            </div>
```

**Comment by drbgfc** [comment]
Note: We should be using/moving forward with MUI now anyway (typography) vs HTML elements like p h5 etc. So, suggest we do that as part of the fix. This is defintley very low priority though, as you implied. Thanks.

**Comment by kbertodatti** [comment]
@swmuir to check code to make sure this is resolved

**Comment by kbertodatti** [comment]
Opened a new card for the MUI typography. #451
