### ISSUE TITLE
MyCarePlanner - new HHS banner position and close button are based on window size and not fixed to the app's UI itself

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#358]
The newest version of MyCarePlanner employs a banner which I believe is required by the VA.  It persists as a modal layer that can only be closed by clicking an "X" that is positioned to the top-right corner of the banner.

However, the banner changes position relative to the width of the window, and its "X" changes position relative to the banner based on how tall the browser's window is.

For example, here's how it looks with different window sizes:

*Tall and Wide:*
![image](https://github.com/chronic-care/mcc-project/assets/979938/f3676d4c-609b-4832-b555-deb477a4eedb)

*Tall and Narrow:*
![image](https://github.com/chronic-care/mcc-project/assets/979938/7d4615b6-ba50-4a60-bdce-bdda19a0fa79)

*Short and Wide:*
_in this version, the "X" to close the banner is under the banner layer_
![image](https://github.com/chronic-care/mcc-project/assets/979938/0c9520ab-645c-431f-b04b-530f3eab34a9)

*Short and Narrow:*
![image](https://github.com/chronic-care/mcc-project/assets/979938/2b302f39-5a5b-4fee-a4a2-fc31ad54c032)

Suggest to make the banner position relative to the rest of the app UI, and not relative to the size of the window in which it's being displayed.

**Comment by kbertodatti** [comment]
This is updated, but the code needs to be merged properly.

@sai-kiran-r include the code in your fork.
