### ISSUE TITLE
MyCarePlanner - Auto-logout timer erroneously appears on "You have been logged out" screen

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#359]
I came into the office this morning and fired up my computer, reloaded browser tabs from last night.  One of them had been running MyCarePlanner, now displaying its "You have been logged out" screen due to the auto-logout functionality, which is good and expected.

About 15 minutes later, I see on that screen appear the "Are you still there?" dialog that would normally show up in the app to allow the user to continue the session.

![image](https://github.com/chronic-care/mcc-project/assets/979938/1c29b5c2-9083-4e5e-8659-67cec25f7bb3)

This probably doesn't need to fire on the page where the user is already logged out.

Minor thing, but wanted to bring it to your attention.

**Comment by kbertodatti** [comment]
Kiran is unable to recreate the scenario.

**Comment by kbertodatti** [comment]
@sai-kiran-r may have found a fix and is working on this.

**Comment by kbertodatti** [comment]
Fix for Autologout timmer: I passed the current state of logout page into the timer page, in this case whenever there is Logout page on UI the timer wont popout.
