### ISSUE TITLE
Create filter implementation

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#363]
Create outline for implementation
<img width="335" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK05GQWc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--277339716fbd59a12e580e70b833dc9f6828d419/image.png" alt="image.png" />

1. Work with links from launch endpoints
2. Display labels from the endpoints
3. Add env. variable to hide filter if user is only logged into 1 EHR

**Comment by savanahmueller** [comment]
Reference #27 to see Matt's comments.

**Comment by savanahmueller** [comment]
Add env variable to show filter as blank. 
If there is no second provider, it should not show filter.
