### ISSUE TITLE
eCarePlanner v3.1.2 : Questionnaire queries missing required "id" parameter 

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#371]
It appears that _Questionnaire_ queries being executed from eCarePlanner v3.1.2 are passing _code_ and _summary_ parameters to the FHIR server, but are generating `400` responses due to a missing _id_ parameter.  "Only an _ID search is allowed."

I'm not sure how to fix this, if a Questionnaire can only be looked up by _id_, it seems the only way to get one is for something else to reference it, and to pull the _id_ from that reference.

![image](https://github.com/chronic-care/mcc-project/assets/979938/73601651-d4b7-4f8b-bb10-6f3e721ca4c3)

Logging here for tracking purposes

**Comment by kbertodatti** [comment]
Will be addressed when we turn query off.

**Comment by kbertodatti** [comment]
Default to turn off querying questionnaire. Add env. to toggle.
