### ISSUE TITLE
eCarePlanner v3.1.2 - all Medication names are showing as "( MedicationRequest )"

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#372]
Active Medications in eCarePlanner v3.1.2 are all displaying as "( MedicationRequest )" which isn't correct or useful -

![image](https://github.com/chronic-care/mcc-project/assets/979938/0dec499a-41a1-4988-a0ce-7820c9d9b456)

**Comment by swmuir** [comment]
<img width="2000" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3RJQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--fd5eb2aead3049ea46246a6754d4efa1d376d39d/image.png" alt="image.png" />

**Comment by mattStorer** [comment]
@swmuir what is that link?  if I click it I get this:

![image](https://github.com/chronic-care/mcc-project/assets/979938/60d31e48-3946-4f62-86b9-9cd612d71976)

**Comment by kbertodatti** [comment]
Same bug as #374

**Comment by mattStorer** [comment]
this is verified resolved in eCarePlanner 3.1.4.
