### ISSUE TITLE
Turn off HHS warning banner for MyCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#378]
Default to off.

**Comment by kbertodatti** [comment]
Added an env variable name REACT_APP_HHS_BANNER in the .env file. Changing this value to true will enable the HHS warning banner on the app and changing it to false will disable the HHS warning banner.

**Comment by mattStorer** [comment]
just a quick comment on the HHS warning banner in version 2.2.0.  I set `REACT_APP_HHS_BANNER="false"` as an environment variable on the command line, but it appears that a value of `false` still means that the banner _should_ show, as it's showing in that case:

![image](https://github.com/chronic-care/mcc-project/assets/979938/79ef0dfc-ba52-45a0-b655-a484ff3dc56f)

also the progress bar is still displaying on top, as you can see in the screenshot.

Setting `REACT_APP_HHS_BANNER="true"` continues to disable the banner.

Not a blocker as we can still turn it off, I just wanted to bring this to your attention.  FYI
