### ISSUE TITLE
Update CQL Summary for Goals in MyCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#379]
Update Goal CQL to display both address Observation (currently only addresses Condition).
Update CQL to include lifecycle.status and achievement.status.

**Comment by drdavec** [comment]
@swmuir Created a pull request to merge this change into develop branch.

<img width="516" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN09VQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--efe92fbeab6f00a1a262a32f3151d7b72f15bf42/Screenshot%202024-04-25%20at%201.08.24%E2%80%AFPM.png" alt="Screenshot 2024-04-25 at 1.08.24 PM.png" />
