### ISSUE TITLE
Update UI for header component in eCarePlanner to match new wireframes

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#383]
Update header component to match wireframe: https://www.figma.com/file/fYM0MNFOh2EjBN2nBXj3Nu/MCC-eCare-Clinician-App?type=design&node-id=1310%3A19728&mode=design&t=nZAwcCRWf9jiqRva-1

**Comment by savanahmueller** [comment]
Focusing only on the header. Should be complete by 5/23.

**Comment by savanahmueller** [comment]
Changed some global settings and working on matching header colors. <img width="1502" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2Q4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1b32ef6c5940e67fcf712bc235df90a49172d570/Screenshot%202024-06-20%20110912.png" alt="Screenshot 2024-06-20 110912.png" />
<img width="1504" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2g4QlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a850b6462bc45cb79559988d0b7330d65969efdb/Screenshot%202024-06-20%20110903.png" alt="Screenshot 2024-06-20 110903.png" />

**Comment by sravandigitalhie** [comment]
Modified the Demographics, Navigation UI to Align with the new wireframes:

<img width="1918" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBL3VCQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ee7bb5b376b504f45f76471a98e47aa979a1640b/image.png" alt="image.png" />

**Comment by kbertodatti** [comment]
Sravan is resolving merge conflicts and will raise a PR after.

**Comment by savanahmueller** [comment]
Should be done by 6/28
