### ISSUE TITLE
Patient data cards reference From Launcher (dynamic)

### ISSUE THREAD

**Issue by MichelleBobo** [chronic-care/mcc-project#396]
The patient data cards are also referencing From Launcher (dynamic), which will be confusing to patients. There is a line below that that says Source OHSU, which is probably enough. The external data cards for this test patient (Epic sandbox),  seem to only include From and not Source. How do we clean this up so that it is consistent and sensible to patients?

<img width="677" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOUhHQkE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4cee59a5db3e9f5838566ce0068341babdbd2b2b/image.png" alt="image.png" />

**Comment by kbertodatti** [comment]
@drbgfc to do a search for "Launcher (Dynamic)" language to see if this is still present.

@drdavec to re-add the changes he made to Goal (lifecycle status) and change the From/Source to just "From" and add logic to show provenance. If provenance isn't available, show endpoint name.

**Comment by drbgfc** [comment]
Updated Launcher (Dynamic) to "Original provider"
