### ISSUE TITLE
eCarePlanner 3.1.3 - all Medication names are blank

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#401]
in eCarePlanner 3.1.3, it appears that the previous issue (#372) has been resolved, insofar as medication names are no longer being displayed as "( MedicationRequest )".  however, what is now being displayed there is nothing at all (yellow highlights are mine):

![image](https://github.com/chronic-care/mcc-project/assets/979938/a3def88e-6b72-4d7f-b8f1-f4921e212378)

Suggest to pull the medication name from _MedicationRequest.medicationReference.display_, or from the referenced _Medication_ resource, if that isn't available

**Comment by kbertodatti** [comment]
Our code may be written to use codeable concept but Epic rarely returns it this way. Fix: Use display string of medication reference.

**Comment by mattStorer** [comment]
this is verified resolved in eCarePlanner 3.1.4.
