### ISSUE TITLE
eCarePlanner 3.1.3 - Active Diagnosis "Diagnosis First Recorded" is off-by-one.  Also "Date of Initial Diagnosis" all read "Invalid Date" 

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#402]
in eCarePlanner 3.1.3, all "Date of Initial Diagnosis" fields read "Invalid Date".  Not sure why this is as I'm not sure where this comes from, so it's hard for me to say what it should be.  But I wanted to bring this up as a potential issue.

While investigating this, I noticed that the displayed "Diagnosis First Recorded" dates are off-by-one.  Likely a timezone issue I suspect, same as what afflicted the Patient's Birth Date in issue #344.

![image](https://github.com/chronic-care/mcc-project/assets/979938/734ad379-7bb1-4b80-92ed-f5ff628da4a7)

**Comment by kbertodatti** [comment]
@swmuir to do a search to see all the places we're converting to a date and ensure the timezone fix is implemented.
