### ISSUE TITLE
MyCarePlanner 2.2.0 sort logic is keeping resources from different sources separated when they should be combined

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#404]
_(this is a copy of a comment I added to the original ticket #27, which is now closed; creating new ticket to represent this issue for visibility)_

just checking status of the sort/filter logic in MyCarePlanner 2.2.0.

firstly, the sort/filter UI looks WAY better, so thank you for those fixes!  the filtering also works as intended, so that's great.

that's the good news.

the bad news is that the sorting is still sorting only within the context of source groups, and not all together.  that is, all OHSU resources are sorted first (A-Z or Z-A), then (for example) Cerner resources are sorted (A-Z or Z-A).

screenshots:

A-Z, OHSU then Cerner:

![image](https://github.com/chronic-care/mcc-project/assets/979938/8a1b4620-d6d2-4f9c-9f72-617414c47234)

Z-A, OHSU then Cerner:
![image](https://github.com/chronic-care/mcc-project/assets/979938/0787220b-3d3c-4c52-a141-ea172b40a530)

so it looks like a little more needs to be done on this to get it where it needs to be.

**Comment by kbertodatti** [comment]
Closing because we have a card for this already. Referenced this card with the screenshots in that one.
