### ISSUE TITLE
Bootstrap first iteration of MyCarePlanner with SDS

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#413]
Goal: Develop something in MyCarePlanner to do some initial test around SDS interaction that Tim is working on. Want to see if there are any big issues with the current design approach.

https://docs.google.com/document/d/1uqD4I8m7FOrcN2sr0HChr6mucIOUEoVYf5mEuI4kEcQ/edit#heading=h.5sks6y3h2u1f
Look at: **Reading and Writing App Authored Content**

Open questions:
- How do we connect the created Linkage with the OHSU patient?

Acceptance criteria:
1. MyCarePlanner queries for Linkage Resource.
2. If no Linkage Resource exists, then create a new patient and save it to the SDS.
3. Get Linkage and ID of local Patient.

**Comment by savanahmueller** [comment]
OHSU determined SDS cannot work outside of OHSU. Meeting on Friday 6/21 4-5 ET and Monday 6/24 3-4 ET. Will share update then.

**Comment by savanahmueller** [comment]
SDS is working in our environment (azure, local). Sean updating code to be ready this afternoon (7/2). Send Beta version over to Matt today (7/2).

**Comment by kbertodatti** [comment]
Remaining work: Parsing of the Linkage we're getting from the SDS to get the PatientID and have the PatientID available. Should take about an hour.

@swmuir to create a beta version and send it to Matt.
