### ISSUE TITLE
Display all goals in eCarePlanner to include status other than active

### ISSUE THREAD

**Issue by MichelleBobo** [chronic-care/mcc-project#415]
Change the query in eCarePlanner to:
Goal?lifecycle-status=active,completed,cancelled

*Add column for "Lifecycle Status" and make the label "Goal Status". Add this column to the left of Achievement Status.
*Remove column for "Priority"

**Acceptance Criteria**
- Displays goals that are active, completed, and cancelled
- Displays lifecycle status in "Goal Status" column for each goal
- Priority column is removed

_Additional rationale for removing Priority_
- Epic supports priority but using proprietary codes (not interoperable-friendly)
- Latest build of US Core (v7), priority is not mentioned for Goal
- No current support via eCare apps for designating priority for Goal so clinicians may not find the functionality helpful
- More discovery is needed for designating priorities among different members of the care team

Can tackle this card at the same time as #462 if desired.

Context: Our test patient had 6 goals documented in MyCarePlanner and only one of them was visible in eCarePlanner. It is my understanding that ALL entered goals should be displaying.

![image](https://github.com/chronic-care/mcc-project/assets/147000980/61fe96cf-a81e-4fba-9689-2bccf40fbe2b)
![image](https://github.com/chronic-care/mcc-project/assets/147000980/870ab07b-1888-4a80-a17d-43292f112e7f)

**Comment by drdavec** [comment]
I suspect that eCarePlanner is only including 'active' Goal lifecycleStatus.  While recently updating MyCarePlanning to display Goal status, I also expanded the status types to align with those supported by Epic.

Change the query in eCarePlanner to:
Goal?lifecycle-status=active,completed,cancelled
