### ISSUE TITLE
Sort conditions by patient-friendly name

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#417]
Sort A<>Z should be by the highlighted name - "Common name".

Dave to check logic for the Common name to make sure it's always populated.
Sravan to change sort to the Common name field.

<img width="676" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzVIQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--425a04998cd88e58eae72e83b62d00d21f17bd7e/image.png" alt="image.png" />

**Comment by savanahmueller** [comment]
Updated but currently inconsistency in sorting by Common Name.

**Comment by kbertodatti** [comment]
@sravandigitalhie has completed the sort AZ by Common Name.
He also updated the date sort to RecordedDate (instead of OnsetDate).

@drdavec will check the US Core spec to see if RecordedDate is required and if not, what the desired approach is if the value is null.
