### ISSUE TITLE
eCarePlanner 3.1.5 - Care Team tab is blank with errors "_a.reference is undefined"

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#418]
In eCarePlanner 3.1.5, deployed to resolve issue #414, it appears that the original error that was the basis for that ticket has been resolved.  However, a new error has replaced it, "_a.reference is undefined" :

```
TypeError: _a.reference is undefined
    theParticipation contact.util.ts:70
    transformToMccContact contact.util.ts:70
    mappedPatientContacts contact.ts:43
```

![image](https://github.com/chronic-care/mcc-project/assets/979938/1ae55160-af2a-4a94-800a-6b979bc1f95b)

I’ll also take this opportunity to reinforce the idea that there can be – and in all likelihood will be - a lot of missing data in resources, and that the app should be able to gracefully handle such situations.  In fact, almost all elements of FHIR resources are optional and may be omitted.  I conceive “gracefully handling” such missing data as omitting the missing elements from processing and display without error, while continuing to process and display those elements that do exist.

on a trivial side note, from a grammatical perspective, it seems that `theParticipation` refers to a _participant_, and ought to be named `theParticipant` instead.  the variable references an individual, not an action.

**Comment by swmuir** [comment]
Please verify still an issue with eCarePlanner  v3.1.6
