### ISSUE TITLE
eCarePlanner 3.1.5 - Care Team - some names missing, showing "MISSINGGIVEN"

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#419]
It was reported in eCarePlanner 3.1.5 that some Care Plan data is coming through in a way, displaying "MISSINGGIVEN undefined" as the name.

![image](https://github.com/chronic-care/mcc-project/assets/979938/1bf355f5-6321-479c-8743-c05684d7619d)

Christina investigated this a bit, who provided the following information:

> Highlighted in yellow is the provider that is listed as MissingGiven. We are returning the outside provide or the provider that is via Care Everywhere. Let me know if you have any questions.

![image](https://github.com/chronic-care/mcc-project/assets/979938/980e0886-9c44-4d90-89fe-455c9f3b8d26)

Attached is the full CareTeamResponse, in the hope that it will be useful in sorting this out:
[CareTeamResponse.txt](https://github.com/user-attachments/files/15873698/CareTeamResponse.txt)

**Comment by swmuir** [comment]
Meld does not support  _family element - 

"name": [{
                        "use": "usual",
                        "text": "Christopher Terndrup, MD",
                        "_family": {
                            "extension": [{
                                    "valueCode": "masked",
                                    "url": "http://hl7.org/fhir/StructureDefinition/data-absent-reason"
                                }
                            ]
                        }
                    }
                ],

**Comment by swmuir** [comment]
Fixed in eCarePlanner  v3.1.6
