### ISSUE TITLE
eCarePlanner 3.1. 6 - add email disclaimer to Care Team tab

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#420]
eCarePlanner 3.1.6 is now displaying Care Team information, which is great, thank you for sorting that out!

However, email addresses are displayed for Care Team members, which Dr. Dorr identified as a potential security / HIPAA concern that can be adequately addressed with a disclaimer.

The concern is that those who can view this screen _may_ use the provided email to send confidential / protected information to Care Team members, which is not a secure vector.

Suggest to add the following disclaimer to the top of the Care Team tab:

"**Note: Email addresses provided here are for informational, or general correspondence purposes only, and should not be used to communicate PHI, PII, or otherwise protected patient information.**"

**Comment by savanahmueller** [comment]
Confirm for Clinician facing app (eCarePlanner)
