### ISSUE TITLE
Update UI for Health Concerns tab eCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#422]
https://www.figma.com/design/fYM0MNFOh2EjBN2nBXj3Nu/MCC-eCare-Clinician-App?node-id=1104-4708&m=dev

Main purpose: Make the tables "ready" for accordion collapse work.

For recording physician use "asserter"
https://www.hl7.org/fhir/R4/condition.html

Mapping will be found in the common data services: https://github.com/chronic-care/e-care-common-data-services

**Comment by savanahmueller** [comment]
Aim for completion by 7/9.

**Comment by savanahmueller** [comment]
Aim to complete for next release by Tuesday, July 16.
