### ISSUE TITLE
Investigate logout protocol for MyCarePlanner for timeout

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#425]
It looks like the timeout removes local storage. @drdavec will confirm.

If user just closes the tab, then tokens are still stored and available for the life of the token.

<img width="787" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM09KQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--35139b3461f9cb935f5a70996a49b3e5c1f7d572/image.png" alt="image.png" />

**Comment by kbertodatti** [comment]
From Dave:  testing the current behavior for timeout.  I set the timeout to 5 minutes.  If I open the app and go off to other work, it does correctly timeout after 5 minutes and I cannot refresh the app to restart, I must relaunch.  However, when I relaunch within a hour, the app does remember the Epic Sandbox access token and reloads the same Epic patient without prompting me to login and select the patient.   After an hour, this no longer happens.  So it appears the access token is saved in user browser state after app timeout.

You can test this in the CarePlanning sandbox by launching the app where the timeout is set to 5 min in this build: https://chronic-care.github.io/mycareplanner/launch.html?iss=https://gw.interop.community/CarePlanning/data

However, you need to also login to Epic sandbox for a realistic test, because the MELD sandbox login is saved in the browser outside of our app and does not prompt re-login to MELD even a few hours later.

**Comment by drbgfc** [comment]
Once we add a logout button and have it call handleLogout - localStorage will be fully handled (cleared)
