### ISSUE TITLE
Add logout button MyCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#427]
Add logout button UI
Implement logout to dump tokens and session ID (same implementation as session time out #426)

Wireframe for logout button: https://www.figma.com/design/28Tvzsvn9S9wEYCQvmzfUT/MCC-eCare-Patient%2FCG?node-id=458-6933&t=2hwUPHGoQpE6gnCV-1

**Comment by savanahmueller** [comment]
Aim for release on 7/16
