### ISSUE TITLE
Stable build for the apps

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#43]
services:
  mccservices:
    image: swmuir/mccservices 
    container_name: tmccservices
    domainname: mccservicesopen
    network_mode: default
    environment:
       FHIR_SERVER : https://gw.interop.community/CarePlanningQA/open
       SECURE_FHIR_SERVER : OBE
    ports:
      - "8081:8081"
    restart: always
  providersmartapp:
    image: swmuir/providersmartapp
    container_name: tprovidersmartapp
    domainname: mccservicesopen
    network_mode: default
    environment:
      CLIENT_ID :  4726480d-f01f-478b-bbd1-4abfc4df969d
      API_SERVER : http://localhost:8081
    ports:
      - "80:80"
    restart: always

**Comment by kbertodatti** [comment]
@drdavec to test

**Comment by swmuir** [comment]
[https://app.zenhub.com/files/430794588/c54a6d86-1112-4b2f-bd5f-b277b81fe191/download](https://app.zenhub.com/files/430794588/c54a6d86-1112-4b2f-bd5f-b277b81fe191/download)

Attached is the docker compose to start up the server and client using the client ids 
The client id will be the one from the smart on fhir configuration
