### ISSUE TITLE
Display of history of results for Tests/Labs and Vitals - CQL

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#441]
As a patient, when I click on the card for one lab, it will expand to show the 10 most recent readings.

Update CQL logic to provide a list of historical summaries.
Disclaimer (History from that provider)

**Comment by drdavec** [comment]
CQL is updated and tested, history is now included within the ObservationSummary for both labs and vitals.


export interface ObservationSummary {
  DisplayName: string,
  ConceptName: string,
  Date?: string,
  ResultText: string,
  ResultValue?: number,
  ResultUnits?: string,
  ReferenceRange?: string,
  Interpretation?: string,
  Flag?: boolean,
  Performer?: string,
  Notes?: string[],
  Provenance?: ProvenanceSummary[],
  LearnMore?: string,
  History?: ObservationHistory[]
}

export interface ObservationHistory {
  Date?: string,
  ResultText: string,
}

**Comment by drdavec** [comment]
Tested by adding the history list at the bottom of each lab or vital in the display.  First screenshot from MELD CarePlanning data, second screenshot from Epic Sandbox

<img width="503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMlcxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--25ee2254b6dac57da19c39c0140ab844ca8330fc/Screenshot%202024-09-05%20at%205.57.53%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 5.57.53 PM.png" />
<img width="598" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmExQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--451f841e988eb35daf5090c69bb335e9a528d957/Screenshot%202024-09-05%20at%206.00.34%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 6.00.34 PM.png" />
