### ISSUE TITLE
Health Concerns is unpopulated in eCarePlanner

### ISSUE THREAD

**Issue by MichelleBobo** [chronic-care/mcc-project#448]
Providers are reporting that the Health Concerns section always seems to be unpopulated in eCarePlanner. Can you clarify what is supposed to be here and confirm if it is working correctly?

![image](https://github.com/user-attachments/assets/33ce807a-1a0d-443e-be13-e22cdb801371)

**Comment by kbertodatti** [comment]
eCarePlanner shows the following:
All Conditions where category=problem-list-item, clinical-status=active
All Conditions where category=health-concern, clinical-status=active

If the data do not match those then it won't be shown.
