### ISSUE TITLE
Add configuration to turn off non-required category sections on Health Status Evaluation & Outcomes (eCarePlanner)

### ISSUE THREAD

**Issue by MichelleBobo** [chronic-care/mcc-project#450]
Add configuration for other category sections:
- False = Sections where category is procedure, imaging, activity, exam, and therapy are hidden
- True = All sections are shown

Reference: https://docs.google.com/document/d/1pgYGFHIosichOOZcM_9fPXxDJtYNQ1eF7e2brpgE_zU/edit?usp=sharing

<<From Michelle>>
Several sections on the Health Status Evaluation & Outcomes tab are consistently empty, even with testing of real and complex patients. These sections are: Exam, Imaging Results, Activities, Procedure Results and Therapy. Are these sections supposed to be populated with actual data? If not, perhaps they should be removed. Please clarify what is expected to be coming through in these sections or remove if not functional.

![image](https://github.com/user-attachments/assets/227338d5-bc57-4db9-8451-0580b9c03c40)

**Comment by sravandigitalhie** [comment]
The categories 'Procedure,' 'Imaging,' 'Activity,' 'Exam,' and 'Therapy' have been successfully hidden. A screenshot has also been attached for reference.

<img width="1625" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeG1nQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb4874ed88076cc0e2415abe63fd3b3b28e32971/image.png" alt="image.png" />

**Comment by kbertodatti** [comment]
Change "History" to "Social History"
