### ISSUE TITLE
Display history of results for Tests/Labs and Vitals - UI

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#458]
As a patient/caregiver, I want to see a history of previous lab values so that I can better understand trends. 

Figma: https://www.figma.com/design/28Tvzsvn9S9wEYCQvmzfUT/MCC-eCare-Patient%2FCG?node-id=488-6226&t=v3X9rpXdYOUEKrSW-1

Uses MUI Card Complex Interaction
* MUI: https://mui.com/material-ui/react-card/#complex-interaction
* Blog: https://refine.dev/blog/material-ui-card/#material-ui-card-interactions

Requirements:
* Clicking on the down Chevron expands the card to show a list of previous lab values (value, units, and date).
* Show list of additional 10 most recent labs from most recent on top to oldest on bottom.
* Only one card can be expanded at a time.
* For cards that don't have additional history of values, do not show "History of labs" with down chevron.

**Comment by savanahmueller** [comment]
No history data as of 9/5. Dave is working on the data array. Sravan will work on the UI but it will currently show empty space. Two columns of value and date.

**Comment by drdavec** [comment]
@sravandigitalhie I added the history display to both LabResultList and VitalsList so you can see how to access the history values for display.  You just need to move these into a pull-down list.

Also note that for VitalsList, I added specific logic to show both date and time, but ONLY for Home Blood Pressure.  This is based on client discussion, where Home BP are often taken several times, and it would be helpful to see the time when several are taken in one day.

<img width="503" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMmkxQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e9098bccd8e6a9bdb1ba55d3a198f4c32e48762c/Screenshot%202024-09-05%20at%205.57.53%E2%80%AFPM.png" alt="Screenshot 2024-09-05 at 5.57.53 PM.png" />

**Comment by sravandigitalhie** [comment]
Have integrated Accordion for the records which are having the "history" for both Vitals and Labs

Vitals:
<img width="445" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN2pRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--472359b4e7a00bc6defa59ea7801d73c32ce0544/image.png" alt="image.png" />

<img width="454" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN25RQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--50adbc638cb76c3f94d4490f885169eef1e0572d/image.png" alt="image.png" />

<img width="462" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3JRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e05c107b861f67ef3134453ea53a5e1b1a65797/image.png" alt="image.png" />

<img width="450" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3ZRQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--da1e0f8fc17f493816e9b5ab8742b9635aefa131/image.png" alt="image.png" />
