### ISSUE TITLE
Remove paging on Medication List

### ISSUE THREAD

**Issue by drdavec** [chronic-care/mcc-project#46]
In provider app, remove paging limit on medication list, display all active medications on one screen.
Create test patient with 20-30 meds to evaluate if unlimited displays well, or to increase page size from 10 to 20.

OHSU Feedback:
Medication list defaults to 10 – hard to see ‘next page’ button, so default to more than 10 (if not all).

**Comment by kbertodatti** [comment]
Need to create test data with more than 20 active meds to QA this feature.
