### ISSUE TITLE
Change "Date" to "Order Date" for Medications MyCarePlanner

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#460]
Change label for "Date:" to "Order Date:" on the Medications tab in MyCarePlanner. Confirm this is pulling from the Order Date FHIR data element.

**Comment by drdavec** [comment]
MedicationRequest.authoredOn date is displayed.  Changed label to "Ordered On".

Hide display if AuthoredOn date is absent (don't display "Unknown")

<img width="932" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBKzIvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--34f22e73efd2446f22d9db2d22ba51197936060a/Screenshot%202024-09-09%20at%205.49.11%E2%80%AFPM.png" alt="Screenshot 2024-09-09 at 5.49.11 PM.png" />

**Comment by drdavec** [comment]
Complete, will move to QA when code is committed and included in a build along with other changes.
