### ISSUE TITLE
Revise provider app top banner

### ISSUE THREAD

**Issue by drdavec** [chronic-care/mcc-project#47]
In provider app top banner, remove "Ethnicity" and add "DOB".
Request feedback on field name for DOB, e.g. "Date of Birth", "Birth Date", or "DOB"

OHSU feedback:
* Patient DOB would be helpful in top banner bar. It's necessary for ID confirmation when trying to coordinate care with other groups
* Race/ethnicity thing … why both? (referring to banner at top, I believe)

**Comment by kbertodatti** [comment]
Need to review with RTI to confirm whether or not this needs to be identified.

**Comment by swmuir** [comment]
Updated DOB to banner 
Moved race and enthinicity to lower table moved care plan id to upper along with patient id
