### ISSUE TITLE
MyCarePlanner 2.4.1 - remove SDS from third-party endpoint dropdown

### ISSUE THREAD

**Issue by mattStorer** [chronic-care/mcc-project#473]
In MyCarePlanner 2.4.1 (and earlier versions), the SDS is represented in the third-party dropdown list:

![image](https://github.com/user-attachments/assets/1c647490-9979-4421-b7b8-702d68c6490f)

Users should not be given the opportunity to try to connect directly to the SDS in this manner.

**Comment by kbertodatti** [comment]
If there's no ClientID, don't add SDS option to the dropdown.
