### ISSUE TITLE
Improve Medication display

### ISSUE THREAD

**Issue by drdavec** [chronic-care/mcc-project#49]
Improve and expand display of medication details.  Add a pop-up with details.
* Date prescribed, refills permitted
* Dosage
* Notes (comments)

OHSU Feedback:
Need space for info on how the patient is taking the medicine (dosage, frequency, method, gaps, etc.) in addition to prescription details.

https://ecareplan.ahrq.gov/collaborate/display/EC/V1+Pilot+Feedback+Pipeline?preview=/68550689/71434277/Application%20Challenges%20eCare%20Keegan%20121321.docx
(start on pg 4)

**Comment by kbertodatti** [comment]
@swmuir to push to Care Planning QA

**Comment by kbertodatti** [comment]
@swmuir can you add synthea data to the QA sandbox?
