### ISSUE TITLE
Add filter to omit labs without results

### ISSUE THREAD

**Issue by drdavec** [chronic-care/mcc-project#50]
In lab results list, do not show labs without results.

OHSU Feedback:
"No data available" for labs with no values just adds visual clutter. Is it possible to just only show labs that have results available?

**Comment by kbertodatti** [comment]
@drdavec I believe the patient app does this already, right? If so, is it worth hardcoding this filter into the provider app or just wait until the logic is captured in the common data services library?

**Comment by kbertodatti** [comment]
Decision 7/25: add this filter to provider app for September.

**Comment by swmuir** [comment]
updated https://meld.interop.community/CarePlanningQA/apps in Version 1.3 MCC Provider (azurecontainer)
