### ISSUE TITLE
Test CodeableConcept.text fix

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#60]
@emmanurse to write JSON files with positive and negative data. Set up meeting with @swmuir

**Comment by emmanurse** [comment]
Question for Dev: @swmuir  - Is testing needed everywhere codeableConcept is used? Are you using a common method so only spot testing is needed?

**Comment by emmanurse** [comment]
Test Scenarios:
### ![image.png](https://images.zenhubusercontent.com/61aa40adae36b65ba0162435/f841bbb3-4ea2-4253-a19c-8f9ada7e3596)
