### ISSUE TITLE
Configure ecareplan.org with Azure

### ISSUE THREAD

**Issue by drdavec** [chronic-care/mcc-project#62]
Configure eCarePlan.org DNS for use with Azure.
* add basic web server to host a simple home page in HTML
* ecareplan.org/mycareplanner to launch standalone patient/caregiver app
* provider app and API server

**Comment by swmuir** [comment]
Updated https://meld.interop.community/CarePlanning/apps to use demo.ecareplan.org
Need public IP for the mapping so unable to update for patient until we dockerize it

**Comment by kbertodatti** [comment]
@swmuir change url to provider.ecareplan.org

**Comment by swmuir** [comment]
updated to provider.ecareplan.org
