### ISSUE TITLE
Support Goal within a facade

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#67]
Prototype of facade server that combines goal data from supplemental FHIR data store with EHR data.

Done:
1) Add patient app API
2) Create test scripts that demonstrate the UI

**Comment by kbertodatti** [comment]
@swmuir to describe here how this is set up and any thoughts on how it can be reviewed.

**Comment by swmuir** [comment]
curl --location --request POST 'localhost:8081/creategoal?patientId=smart-1557780' \
--header 'Content-Type: application/json' \
--data-raw '{
    "statusDate": "2022-01-01",
    "lifecycleStatus": "proposed",
    "categories": [
        {
            "coding": [
                {
                    "display": "categories"
                }
            ],
            "text": "categories"
        }
    ],
    "priority": {
        "coding": [
            {
                "display": "priority"
            }
        ],
        "text": "priority"
    },
    "description": {
        "coding": [
            {
                "display": "description"
            }
        ],
        "text": "description"
    },
    "useStartConcept": false,
    "startConcept": {
        "coding": [
            {
                "display": "StartConcept"
            }
        ],
        "text": "StartConcept"
    },
    "targets": [
        {
            "measure": {
                "coding": [
                    {
                        "display": "goalMeasure"
                    }
                ],
                "text": "goalMeasure"
            },
            "dueAsText": "DUEASTTEXT"
        }
    ],
    "addresses": [
        {
            "display": "addressses"
        }
    ],
    "notes": [
        "notes"
    ],
    "outcomeCodes": [
        {
            "coding": [
                {
                    "display": "outcomes"
                }
            ],
            "text": "outcomes"
        }
    ],
    "acceptance": [
        {
            "code": "acceptance",
            "priority": {
                "coding": [
                    {
                        "display": "priority"
                    }
                ],
                "text": "priority"
            }
        }
    ]
}'
