### ISSUE TITLE
Copy synthetic test data

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#71]
Copy synthetic data for chronic conditions (limit to 50-100).

**Comment by drdavec** [comment]
We can now run patient/caregiver app with Synthea sandbox (user must have sandbox access) using
https://chronic-care.github.io/mycareplanner/launch.html?iss=https://gw.interop.community/CarePlanning/data 

Had to create a MELD (same in Logica) patient persona in the sandbox for each patient we want to simulate as having a login account.

Two of the patients are children. Can you add a Synthea parameter to generate only patients over 30 years old?

Synthea generates only Condition with "encounter-diagnosis" category, but our app queries only "problem-list-item", which I think is correct.  Investigate synthea options for Condition category.
