### ISSUE TITLE
Investigate work needed to redesign backend of provider app but keep UI

### ISSUE THREAD

**Issue by kbertodatti** [chronic-care/mcc-project#78]
Feasibility LOE to keep UI.
Goal is to align CQL transformations with what the patient/caregiver app now has.
Brief write up on approach and rough estimate of LOE (range is okay).

**Comment by kbertodatti** [comment]
Not sure if this is relevant, but adding it here for your consideration @swmuir 

Propose a specific path forward for the provider app development and enhancements, possibilities include:

a) Retain current Swagger API with app server performing the bulk of value set logic, but replaces app server with a cqf-ruler and HAPI server to execution CQL libraries to process patient data, using same CQL libraries as patient/caregiver app.
b) Remove application server. Execute CQL value set logic within the JavaScript app.
c) Other?

Retain the current app UI design using common Typescript interface structures with the patient app and CQL logic outputs.

**Comment by swmuir** [comment]
Initial SWAG at estimate  - can not seem to post word an spreadsheets directly assume for security
[https://app.zenhub.com/files/430794588/8d71d11b-b7b7-4878-8b40-48ae1f7652f8/download](https://app.zenhub.com/files/430794588/8d71d11b-b7b7-4878-8b40-48ae1f7652f8/download)
